language: node_js
sudo: required
dist: trusty
node_js: stable
install:
  - npm install -g purescript spago@next purs-tidy
script:
  - npm install
  - spago install
  - spago test --pedantic-packages
  - purs-tidy check src test
